[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mosaic-builder"
version = "0.1.0"
description = "A python library for reading photos and building mosaics"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.10.0.84",
    "pandas>=2.2.3",
    "pillow>=11.0.0",
    "puremagic>=1.28",
    "scikit-learn>=1.5.2",
]

[project.urls]
Homepage = "https://your-project-homepage-url.example.com"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
include = ["mosaic_builder/**", "README.md", "pyproject.toml"]

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.4",
    "pytest-xdist>=3.6.1",
    "pytest-timeout>=2.3.1",
    "pytest-asyncio>=0.25.2",
    "pytest-sugar>=1.0.0",
    "black>=24.10.0",
    "autopep8>=2.3.2",
]
