[project]
name = "mosaic-builder"
version = "0.0.1"
description = "A toolkit to build mosaic images from a gallery"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pillow",
  "duckdb",
  "scikit-image>=0.25.2",
]
[project.scripts]
mosaic-builder = "mosaic_builder.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv]
package = true

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
    "nbconvert>=7.17.0",
    "nbstripout>=0.8.1",
    "pre-commit>=4.4.0",
    "pytest>=9.0.2",
    "pytest-sugar>=1.1.1",
    "ruff>=0.14.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E501"]
