[project]
name = "mosaic-builder"
version = "0.0.1"
description = "A toolkit to build mosaic images from a gallery"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "pillow",
  "duckdb",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv]
package = true

[dependency-groups]
dev = [
    "pre-commit>=4.4.0",
]
